version: '3'

services:
  db:
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - movierama_data:/var/lib/postgresql/data
      - movierama_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movierama

  web:
    build: .
   # command: python3 manage.py runserver 0.0.0.0:8000
    command: ./run.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./movierama_app/migrations:/opt/app/movierama_app/migrations

volumes:
  movierama_data: { }
  movierama_backups: { }
